一定程度上修复了逐个通知成员时会卡住的问题，并更新了错误码描述，添加了文档链接
Starlight-Dev-Team/fanbook-bot-tools pull request #102
Opened 2024-04-08 04:50 UTC by fanbook-wangdage

一定程度上 fix #98
![recording](https://github.com/Starlight-Dev-Team/fanbook-bot-tools/assets/124357765/bace7686-56ba-42fa-9370-cef82c275075)  
修改后：  
![recording](https://github.com/Starlight-Dev-Team/fanbook-bot-tools/assets/124357765/ccc32655-47fd-4a1a-af15-278c5895d20f)  
在失败时显示解决方法（文档url）  
文档url:[错误码描述](http://docs.wdg.cloudns.ch/api%E9%94%99%E8%AF%AF%E7%A0%81/)  
文档仓库地址：[文档仓库地址](https://github.com/fanbook-wangdage/apidoc/blob/master/api%E6%96%87%E6%A1%A3/api%E9%94%99%E8%AF%AF%E7%A0%81.md)  
（上一次是我手欠删错库了）

2024-04-08 11:58 UTC, kaikaibenkai requested changes

2024-04-08 11:58 UTC, kaikaibenkai commented on package.json
> +}
```suggestion
}

```
文件结尾需要一个换行

2024-04-08 11:58 UTC, kaikaibenkai commented on pages/feature/send-message.vue
> +    if (res.code === 'ERR_NETWORK') return '无权限发送消息或机器人没有发言api白名单';
```suggestion
    if (res.code === 'ERR_NETWORK') return '无权限发送消息，或机器人不在 /sendMessage API 白名单中';
```

2024-04-08 11:58 UTC, kaikaibenkai commented on pages/feature/send-message.vue
> +        <a href="http://docs.wdg.cloudns.ch/api%E9%94%99%E8%AF%AF%E7%A0%81/" style="color: blue;">点击这里查看解决方法</a>
链接一般使用 [`<AppLink>` 组件](https://github.com/Starlight-Dev-Team/fanbook-bot-tools/blob/0e67fa07c6ed795cbccb3fc415fde717fd434cd8/components/app-link.vue)

2024-04-08 12:06 UTC, kaikaibenkai commented on pages/feature/send-message.vue
> +        <a href="http://docs.wdg.cloudns.ch/api%E9%94%99%E8%AF%AF%E7%A0%81/" style="color: blue;">点击这里查看解决方法</a>
```diff
- 点击这里查看解决方法
+ 不知道如何处理？点此查看常用解决方法
```

2024-04-08 15:31 UTC, fanbook-wangdage commented on pages/feature/send-message.vue
> +    if (res.code === 'ERR_NETWORK') return '无权限发送消息或机器人没有发言api白名单';
是的

2024-04-09 11:32 UTC, kaikaibenkai requested changes

2024-04-09 11:32 UTC, kaikaibenkai commented on utils/bot.ts
> +  '机器人无发送消息api调用白名单' = 10002,
```suggestion
  '机器人不在发消息 API 白名单中' = 10002,
```

2024-04-09 11:42 UTC, kaikaibenkai requested changes
除此之外应该没问题了，不知道为啥 ci 又寄了

2024-04-09 11:42 UTC, kaikaibenkai commented on pages/feature/send-message.vue
> +        <AppLink to="http://docs.wdg.cloudns.ch/api%E9%94%99%E8%AF%AF%E7%A0%81/">
链接 403 了，除此之外应该没问题了
（ci 不知道为什么又寄了）

2024-04-09 14:02 UTC, fanbook-wangdage commented on pages/feature/send-message.vue
> +        <AppLink to="http://docs.wdg.cloudns.ch/api%E9%94%99%E8%AF%AF%E7%A0%81/">
我这边可以，之后我试试cdn

2024-04-09 14:24 UTC, kaikaibenkai commented on pages/feature/send-message.vue
> +        <AppLink to="http://docs.wdg.cloudns.ch/api%E9%94%99%E8%AF%AF%E7%A0%81/">
现在好了
tip: Vuepress 1 技术栈已经严重过时，建议使用 [Vitepress](https://vitepress.dev) 或者还在 rc 阶段的 [Vuepress 2](https://v2.vuepress.vuejs.org)

2024-04-09 14:25 UTC, kaikaibenkai approved these changes
LGTM

2024-04-09 14:26 UTC, merged